version: '3'

services:
        zookeeper:
                image: zookeeper:latest
                restart: always
                container_name: zookeeper
                hostname: zookeeper
                ports:
                        - 2181:2181
                
        main:
                #restart: always
                build: .
                container_name: main
                hostname: main
                command: /sbin/init
                privileged: true
                tty: true
                ports:
                        - 8081:8081  # storm UI
                        - 9092:9092  # kafka
                depends_on:
                        - zookeeper
                
        mitsimlab:
                #build: ./MITSIMLab
                image: centos:centos7
                container_name: mitsimlab
                #hostname: mitsimlab
                tty: true
                volumes:
                        - ./MITSIMLab/pgsql/data:/var/lib/pgsql/data
                        - ./MITSIMLab/mitsim/data:/usr/local/MITSIMLab/data
                ports:
                        - 5432:5432
