FROM ubuntu:latest

RUN apt-get update &&\
    apt-get install -y git openjdk-11-jdk maven python3 ruby wget vim sudo gcc g++ gcc-multilib g++-multilib make init systemd lsb-release net-tools lftp gnupg gnupg2 librdkafka-dev pkg-config libglib2.0-dev

#install storm
WORKDIR /usr/local
RUN wget https://archive.apache.org/dist/storm/apache-storm-2.2.0/apache-storm-2.2.0.tar.gz && \
    tar -zxvf apache-storm-2.2.0.tar.gz && \
    mv apache-storm-2.2.0 storm && \
    rm apache-storm-2.2.0.tar.gz

#setup storm
RUN mkdir /usr/local/storm/data && \
    echo -e "storm.zookeeper.servers:\n\t- "localhost"\nstorm.local.dir: "/usr/local/storm/data"\nnimbus.seeds: ["localhost"]\nsupervisor.slots.ports:\n\t- 6700\n\t- 6701\n\t- 6702\n\t- 6703\nui.port: 8081" >> /usr/local/storm/conf/storm.yaml

#symlink python
RUN ln -s /usr/bin/python3 /usr/bin/python

#install kafka
RUN wget https://downloads.apache.org/kafka/3.3.2/kafka_2.12-3.3.2.tgz && \
    tar -zxvf kafka_2.12-3.3.2.tgz && \
    mv kafka_2.12-3.3.2 kafka && \
    rm kafka_2.12-3.3.2.tgz

#copy files generated by data generator in mitsimlab container
COPY --chown=root:root MITSIMLab/mitsim/data/cardatapoints.out MITSIMLab/mitsim/data/historical-tolls.out MITSIMLab/mitsim/data/maxCarid.out /usr/local/lrb/dgoutput/

#copy files for producing generated data via kafka
WORKDIR /usr/local/lrb/datadriver
COPY --chown=root:root datadriver/* /usr/local/lrb/datadriver/

#start kafka broker service in background and create topic lrb
RUN /usr/local/kafka/bin/kafka-server-start.sh kafka_server.properties &
RUN /usr/local/kafka/bin/kafka-topics.sh --create --topic lrb --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1

#compile and link datadriver files
RUN g++ -c `pkg-config --cflags glib-2.0 rdkafka` DataFeeder.cpp && \
    g++ -c LRDataProvider.cpp && \
    g++ -c MemTuples.cpp && \
    g++ -c Tuple.cpp && \
    g++ -o datafeeder DataFeeder.o `pkg-config --libs glib-2.0 rdkafka` -lpthread LRDataProvider.o MemTuples.o Tuple.o
