version: '3'

services:
        zookeeper:
                image: zookeeper:latest
                restart: always
                container_name: zookeeper
                hostname: zookeeper
                ports:
                        - 2181:2181
                networks:
                        - mynet
                
        data-producer:
                build: ./data-producer
                container_name: data-producer
                hostname: data-producer
                tty: true
                volumes:
                        - ./data-producer/kafka_connect:/usr/local/lrb/kafka_connect
                ports:
                        - 9092:9092 # kafka
                depends_on:
                        - zookeeper
                networks:
                        - mynet

        storm-nimbus:
                build: ./storm/nimbus
                container_name: storm-nimbus
                hostname: storm-nimbus
                command: /sbin/init
                privileged: true
                tty: true
                volumes:
                        - ./storm/nimbus/storm_app:/usr/local/storm_app
                        - ./storm/nimbus/toll_notifications:/usr/local/toll_notifications
                ports:
                        - 8081:8081  # storm UI
                depends_on:
                        - zookeeper
                networks:
                        - mynet

        storm-supervisor:
                build: ./storm/supervisor
                container_name: storm-supervisor
                hostname: storm-supervisor
                tty: true
                volumes:
                        - ./storm/supervisor/logs:/usr/local/storm/logs/workers-artifacts
                depends_on:
                        - zookeeper
                networks:
                        - mynet
                
        mitsimlab:
                #build: ./data-producer/MITSIMLab
                image: centos:centos7
                container_name: mitsimlab
                #hostname: mitsimlab
                tty: true
                volumes:
                        - ./data-producer/MITSIMLab/pgsql/data:/var/lib/pgsql/data
                        - ./data-producer/MITSIMLab/mitsim/data:/usr/local/MITSIMLab/data
                ports:
                        - 5432:5432

networks:
  mynet:
    driver: bridge